### PR TITLE
command/help fixes (2)

### PR DESCRIPTION
**Pull request by tdjastrzebski**
I propose more cmd/help fixes.
`list measurements` was missing from command help and does not work.
Note: Fluke 289 stores: recordings, measurements, min/max and peek values
`get measurements` works

btw: `set names` cmd completes ok the name does not seem to actually change

### CODE REVIEW

**Comment by N0ury** [comment]
Here are my comments:
1 - about syntax corrections, it's ok
2 - about ' list measurements'.
You have to know that records of type 'recordings', 'peak', and 'min/max', have two kinds of information. The headers, and the details.
For 'measurements', there is only the detail. That's why I didn't provide a 'list' command.
For the purpose of consistency, I will add it.
3 - the command 'set names' works perfectly for me. on the other hand there was a bug on 'show names' which did not work any more.
Can you please remove the `\r` in line 197 and try again?

**Comment by N0ury** [comment]
I will also keep "show names". I think you might be confused.
"show" allows you to see the DMM configuration
"list" allows to list the measurements made by the DMM.

"show names" allows to see the list of names that you choose when you save the data.
It corresponds to "+Names" of the DMM.

**Comment by tdjastrzebski** [comment]
Thanks!
1. One more cmd improvement idea: `show info` -> `get config`
2. line 678 reads:  `usage();`
I am not Phython expert but VC highlights ";" in red which may indicate some syntax problem, although it compiles

**Comment by N0ury** [comment]
It's now good for line 678 (I hope).

There are 3 "read" commands:
1 - list: to display general informations about stored measurements data
2 - get: to display measurements data (detail)
3 - show: to display DMM configuration data

**Comment by tdjastrzebski** [comment]
What I suggest is getting rid of `show` cmd completely since in its meaning it is very close (if not identical) to `get`.
I think `get config` or `get info` would do equally well.
`set names` I will test later, once I have access to my DMM.

**Comment by N0ury** [comment]
show names and show info have been replaced with get names and get config

**Pull request merged**
